;;; org-version.el --- autogenerated file, do not edit  -*- lexical-binding: t -*-
;;
;;; Code:
;;;###autoload
(defun org-release ()
  "The release version of Org.
Inserted by installing Org mode or when a release is made."
   (let ((org-release "9.4.5"))
     org-release))
;;;###autoload
(defun org-git-version ()
  "The Git version of Org mode.
Inserted by installing Org or when a release is made."
<<<<<<< HEAD:.emacs.d/elpa/org-plus-contrib-20210329/org-version.el
   (let ((org-git-version "9.4.5-elpaplus"))
=======
   (let ((org-git-version "9.4-29-g20374f-elpaplus"))
>>>>>>> origin/master:.emacs.d/elpa/org-plus-contrib-20201102/org-version.el
     org-git-version))

(provide 'org-version)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; coding: utf-8
;; End:
;;; org-version.el ends here
